name: nazarath_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  http: ^0.12.0+4
  http_parser: ^3.1.4
  shared_preferences: ^0.5.10
  carousel_pro: ^1.0.0
  flutter_rating_bar: ^3.2.0
  fluttertoast: ^7.0.4
  url_launcher: ^5.5.3
  provider: ^4.3.2+2
  scrollable_positioned_list: ^0.1.8
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13
  geocoding: ^1.0.5
  spinner_input: ^0.1.2
  geocoder: ^0.2.1
  carousel_slider: ^3.0.0
  dio: ^3.0.10
  path_provider: ^1.6.24
  auth_buttons: ^0.0.4
  uuid: ^2.2.2
  webview_flutter: ^1.0.7
  location_permissions: ^3.0.0+1
  file_picker: ^2.1.6
  #  camera: ^0.6.4+5
  json_annotation:
  charts_flutter: ^0.9.0
  flutter_uploader: ^1.2.1
  flutter_launcher_icons: ^0.7.2+1

  auto_size_text: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/nazarath_logo.png
    - assets/icons/change_password.png
    - assets/icons/favourite.png
    - assets/icons/log_out.png
    - assets/icons/my_address.png
    - assets/icons/my_orders.png
    - assets/icons/men.png
    - assets/icons/nazarath_logo.png
    - assets/icons/privacy_policy.png
    - assets/icons/refer_to_friend.png
    - assets/icons/saved_power.png
    - assets/icons/wallet.png
    - assets/icons/check_up.png
    - assets/icons/check_up_white.png
    - assets/icons/home.png
    - assets/icons/home_white.png
    - assets/icons/news.png
    - assets/icons/news_white.png
    - assets/icons/profile.png
    - assets/icons/profile_white.png
    - assets/icons/stores.png
    - assets/icons/stores_white.png
    - assets/icons/no_image.png
    - assets/icons/edit_profile.png
    - assets/images/no_image.png
    - assets/icons/my_orders.png
    - assets/icons/favourite.png
    - assets/icons/my_address.png
    - assets/icons/saved_power.png
    - assets/icons/wallet.png
    - assets/icons/refer_to_friend.png
    - assets/icons/change_password.png
    - assets/icons/privacy_policy.png
    - assets/icons/log_out.png
    - assets/icons/user.png
    - assets/icons/search.png
    - assets/icons/password.png
    - assets/icons/notification.png
    - assets/icons/mail.png
    - assets/icons/favorite.png
    - assets/icons/fav_active.png
    - assets/icons/cart.png
    - assets/icons/call.png
    - assets/icons/inner_banner.png
    - assets/icons/delete.png
    - assets/icons/minus.png
    - assets/icons/plus.png
    - assets/icons/homebanner.png
    - assets/icons/product1.png
    - assets/icons/empty_cart.png
    - assets/icons/bag.png
    - assets/icons/remove.png
    - assets/icons/banner1.png
    - assets/icons/banner2.png
    - assets/icons/time.png
    - assets/icons/mobile.png
    - assets/icons/location.png
    - assets/icons/house.png
    - assets/icons/calendar.png
    - assets/icons/mailicon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
